// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Airbnb.Lottie;

namespace LottieTest.iOS
{
	public partial class ControlsViewController : UIViewController
	{
        LOTAnimationView WolfAnimation;

		public ControlsViewController (IntPtr handle) : base (handle) { }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            setupWolf();
            this.HideButton.TouchUpInside += HideWolf;
            this.ShowButton.TouchUpInside += ShowWolf;
        }

        void setupWolf() {
            var url = NSUrl.FromFilename("shy_wolf.json");
            this.WolfAnimation = new LOTAnimationView(url);
            this.WolfAnimation.ContentMode = UIViewContentMode.ScaleAspectFill | UIViewContentMode.Center;

            var frame = this.WolfVIew.Frame;
            this.WolfAnimation.Frame = new CoreGraphics.CGRect(0, 0, frame.Width, frame.Height);
            this.WolfVIew.AddSubview(this.WolfAnimation);
        }

        void HideWolf(object sender, EventArgs e)
        {
            this.WolfAnimation.PlayFromProgress(0f, 0.6f, null);
        }

        void ShowWolf(object sender, EventArgs e)
        {
            this.WolfAnimation.PlayFromProgress(0.6f, 1.0f, null);
        }
	}
}
