// This file has been autogenerated from a class added in the UI designer.

using System;

using Airbnb.Lottie;
using Foundation;
using UIKit;
using System.IO;

namespace LottieTest.iOS
{
	public partial class FromAssetsViewController : UIViewController
	{
        bool RadioSelected = false;
        LOTAnimationView RadioAnimation, WolfAnimation;

		public FromAssetsViewController (IntPtr handle) : base (handle) { }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            setupRadioButton();
            setupWolf();
        }

        void setupWolf() {
            var url = NSUrl.FromFilename("shy_wolf.json");
            this.WolfAnimation = new LOTAnimationView(url);
            this.WolfAnimation.ContentMode = UIViewContentMode.ScaleAspectFill | UIViewContentMode.Center;

            var frame = this.WolfView.Frame;
            this.WolfAnimation.Frame = new CoreGraphics.CGRect(0, 0, frame.Width, frame.Height);
            this.WolfView.AddSubview(this.WolfAnimation);

            this.WolfButton.TouchUpInside += (sender, e) => {
                this.WolfAnimation.Play();
            };
        }

        void setupRadioButton() {
            this.RadioButton.TouchUpInside += (sender, e) => RadioClicked();

            var url = NSUrl.FromFilename("check.json");
            this.RadioAnimation = new LOTAnimationView(url);
            this.RadioAnimation.ContentMode = UIViewContentMode.ScaleAspectFit | UIViewContentMode.Center;

            var frame = this.RadioContainer.Frame;
            this.RadioAnimation.Frame = new CoreGraphics.CGRect(0, 0, frame.Width, frame.Height);
            this.RadioContainer.AddSubview(this.RadioAnimation);
            this.RadioContainer.BringSubviewToFront(this.RadioButton);
        }

        void RadioClicked() {
            this.RadioAnimation.AnimationSpeed = (this.RadioSelected) ? -1 : 1;
            this.RadioAnimation.Play();
            this.RadioSelected = !this.RadioSelected;
            this.RadioContainer.BringSubviewToFront(this.RadioButton);
        }
	}
}
