// This file has been autogenerated from a class added in the UI designer.

using System;
using Airbnb.Lottie;
using Foundation;
using UIKit;

namespace LottieTest.iOS
{
	public partial class FromWebViewController : UIViewController
	{
		public FromWebViewController (IntPtr handle) : base (handle) { }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            this.Test1Button.TouchUpInside += Test1Clicked;
            this.Test2Button.TouchUpInside += Test2Clicked;
            this.Test3Button.TouchUpInside += Test3Clicked;
        }

        void Test1Clicked(object sender, EventArgs e) => loadTest(0);

        void Test2Clicked(object sender, EventArgs e) => loadTest(1);

        void Test3Clicked(object sender, EventArgs e) => loadTest(2);

        async void loadTest(int index)
        {
            var url = "";
            switch (index)
            {
                case 0:
                    url = "https://www.lottiefiles.com/storage/datafiles/jW5K6vtuzJFJSxd/data.json";
                    break;
                case 1:
                    url = "https://www.lottiefiles.com/storage/datafiles/30e6f85b10d28931e85c2e0fcffa2f59/data.json";
                    break;
                case 2:
                default:
                    url = "https://www.lottiefiles.com/storage/datafiles/8UjWgBkqvEF5jNoFcXV4sdJ6PXpS6DwF7cK4tzpi/Check%20Mark%20Success/Check%20Mark%20Success%20Data.json";
                    break;
            }

            foreach (var view in this.ContentView.Subviews)
                view.RemoveFromSuperview();

            LOTAnimationView animation = new LOTAnimationView(new Foundation.NSUrl(url));
            animation.ContentMode = UIViewContentMode.ScaleAspectFit | UIViewContentMode.Center;

            var frame = this.ContentView.Frame;
            animation.Frame = new CoreGraphics.CGRect(frame.X, frame.Y, frame.Width, frame.Height);

            this.ContentView.AddSubview(animation);
            this.ContentView.SetNeedsLayout();

            animation.Play();
        }
    }
}
