// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace LottieTest.iOS
{
	public partial class ItemNewViewController : UIViewController
	{
		public ItemNewViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
