// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using MyStrength.iOS.Base;
using UIKit;
using Airbnb.Lottie;

namespace com.MyStrength.iOS.Testing
{
    public partial class TestLottieViewController : BaseViewController, IViewModel
    {
        #region Variables
        #endregion

        #region Life cycle
        public TestLottieViewController(IntPtr handle) : base(handle) { }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            this.ApplyTitle("Lottie Test");
            this.StyleViews();
        }
        #endregion

        #region View Model
        public void ConfigureAccess()
        {
            // TODO: this
        }

        public void StyleViews()
        {
            // TODO: this
        }
        #endregion

        partial void Example1Clicked(NSObject sender) => load(0);

        partial void Example2Clicked(NSObject sender) => load(1);

        partial void Example3Clicked(NSObject sender) => load(2);

        async void load(int idx) {
            foreach (var view in this.Container.Subviews)
                view.RemoveFromSuperview();

            var url = "";
            switch (idx)
            {
                case 0:
                    url = "https://www.lottiefiles.com/storage/datafiles/jW5K6vtuzJFJSxd/data.json";
                    break;
                case 1:
                    url = "https://www.lottiefiles.com/storage/datafiles/30e6f85b10d28931e85c2e0fcffa2f59/data.json";
                    break;
                case 2:
                default:
                    url = "https://www.lottiefiles.com/storage/datafiles/8UjWgBkqvEF5jNoFcXV4sdJ6PXpS6DwF7cK4tzpi/Check%20Mark%20Success/Check%20Mark%20Success%20Data.json";
                    break;
            }

            LOTAnimationView animation = new LOTAnimationView(new Foundation.NSUrl(url));
            animation.ContentMode = UIViewContentMode.ScaleAspectFit | UIViewContentMode.Center;
            animation.Frame = new CoreGraphics.CGRect(this.Container.Frame.X, this.Container.Frame.Y, this.Container.Frame.Width, this.Container.Frame.Height);
            this.Container.AddSubview(animation);
            this.Container.SetNeedsLayout();
            animation.Play();
        }
    }
}
